Add function for Value.Attributes() as a slice
cuelang/cue pull request #529
Opened 2020-09-17 19:27 UTC by verdverm

This enables a user of the Go API to get all attributes so they can inspect them, rather than only being able to ask if a particular attribute exists on a value. Really useful for tools leveraging CUE!

I recall @mpvl might have wanted the return to be a Value or List rather than the slice?

2020-09-30 13:55 UTC, mpvl requested changes

2020-09-30 13:55 UTC, mpvl commented on cue/types.go
> +	// attrs := map[string]Attribute{}
remove line or add TODO.

2020-09-30 13:55 UTC, mpvl commented on cue/types.go
> +// Attributes returne all attributes for the Value.
s/returne/reports/

Note that the old API is a bit broken in that there are now both field attributes and attribute declarations. But that is not the problem of this CL. The attribute declarations could perhaps be obtained through Instance and Struct.

Either way, will be good to be explicit about what this does exactly in the doc comment.

2020-09-30 13:55 UTC, mpvl commented on internal/attrs.go
> +func (a *Attr) SetName(name string) {
Why not just set the name directly? This is an internal type and all other fields are accessed that way. It is a bit confusing to use SetName in this case (unless there is some specific reason to deviate).

2020-09-30 13:55 UTC, mpvl commented on cue/types.go
> +func (a *Attribute) SetName(name string) {
Why would you need to set the Name? I would remove this method.

2020-09-30 13:55 UTC, mpvl commented on cue/types.go
> +func (a *Attribute) Vals() map[string]string {
I would call this `Values` or `Map`, in general Go style is not in favor of using contractions.

But I would remove this method. It is not necessary, as everything can be done without this method and this method exposes implementation details in the API. It also papers over the fact that there can be multiple attributes with the same key in a field.

2020-09-30 13:55 UTC, mpvl commented on cue/types.go
> +func (a *Attribute) Name() string {
Needs doc comment.

2020-10-05 03:40 UTC, verdverm commented on internal/attrs.go
> +func (a *Attr) SetName(name string) {
I think this was a private field prior to v0.3.0-alpha* and it was copied over after the update

2020-10-05 03:44 UTC, verdverm commented
@mpvl did I mess this PR up with a rebase?

I addressed the comments you made but now I see a ton of other commits...

2020-10-05 04:12 UTC, verdverm commented on cue/types.go
> +func (a *Attribute) Vals() map[string]string {
I have this because I'd like to grab all the key/value items in an attribute, and then iterate over those making decisions along the way.

@mpvl I'm confused by your last statement, could you provide an example of what you mean by "multiple attributes with the same key in a field?"

2020-10-05 04:17 UTC, verdverm commented on cue/types.go
> +func (a *Attribute) SetName(name string) {
legacy from pre v0.3.x, removed

2020-10-05 04:17 UTC, verdverm commented on cue/types.go
> +	// attrs := map[string]Attribute{}
removed

2020-10-05 04:18 UTC, verdverm commented on cue/types.go
> +// Attributes returne all attributes for the Value.
changed to "Attribute reports all field attributes for the Value"

2020-10-05 04:18 UTC, verdverm commented on cue/types.go
> +func (a *Attribute) Name() string {
added

2020-10-19 18:23 UTC, verdverm commented
I've found the map to be less ideal, preferring to have the written order maintained, like Cue does elsewhere.

Now thinking a `Attrs.Values() cue.Value` with an underlying struct might make more sense.

Thoughts?

2021-01-27 05:51 UTC, mpvl commented
Note that there are now also attribute at the declaration level. So the API needs to take these into account as well.

2021-01-27 06:10 UTC, verdverm commented
tbh, the Attribute API is the more restrictive one for me than the `Value.Attribute()` vs getting all of them.

Are they both using the same underlying Attribute type?

I'd like to be able to extract all of the content from within the Attribute `()` without having to parse it myself

2021-01-28 19:06 UTC, mpvl commented
I've added a function to get declaration attributes. This may help in coming up with an API that supports both. 

https://cue-review.googlesource.com/c/cue/+/8342

2021-02-17 19:35 UTC, verdverm commented
@mpvl this seems to start supporting the suggestion you made here: https://github.com/cuelang/cue/issues/774#issuecomment-780370962

I have a number of open issues / requests / etc around Attributes, maybe a proposal of sorts is in order for them? I can start a new issue outlining all of these, something like "Attribute(s) API"

thoughts?

2021-02-18 15:40 UTC, mpvl commented
@verdverm : I've started converging on what would be a proper API, so maybe we don't need to go through these lengths.

In a nutshell, we ideally should have only _one_ call for fetching attributes (`Value.Attributes` or `Value.Attrs`) that returns _all_ attributes associated with a value, so field and declaration attributes, but then annotate the kind in the `Attribute` struct. This would allow users to easily interpret declaration attrs of a field as if it were field attrs, etc., without having to jump through hoops and making multiple calls. It also keeps the API tight.

In order to keep the API returning stable when we later introduce more attribute types, this method could take a mask specifying the kind of desired attrs:
```
type AttrKind struct
const (
    FieldAttr AttrKind = 1 << iota
    DeclAttr
    // Possible future attr kinds
    // ElemAttr
    // FileAttr
    // ValueAttr = FieldAttr|DeclAttr|ElemAttr
) 
```

The `Attribute` type could then have a `Kind` method returning this type and `Value.Attributes(mask AttrKind)` would take a mask to only return the requested attributes.

This is not too far off from the implementation in this CL. The heavy lifting of extracting the attrs has been implemented in `internal/core/export`, so this should be fairly straightforward.

The `Attribute` type should have some lower-level non-opinionated functionality, like `Body()` or `Contents()` or something, in addition to the `Name()` method you added (should it be `Name` or `Key`? Either way I guess).

Does this sound reasonable?

2021-02-18 15:42 UTC, mpvl commented on cue/types.go
> +func (a *Attribute) Map() map[string]string {
This method should be removed.

2021-02-18 15:42 UTC, mpvl commented on cue/types.go
> +func (v Value) Attributes() []Attribute {
See CL-level comment.

2021-03-31 09:02 UTC, closed without merging