Allow setting working directory for exec.Run
cuelang/cue pull request #537
Opened 2020-09-22 01:31 UTC by chai2010

Fixes #536

2020-09-22 09:35 UTC, roman-mazur reviewed
I was going to submit a PR too, but you beat me on it :)

We should also update the test, checking that the directory is correctly mapped, similar to how it's done with env vars: https://github.com/cuelang/cue/blob/master/pkg/tool/exec/exec_test.go#L66

2020-09-22 09:35 UTC, roman-mazur commented on pkg/tool/exec/exec.cue
> +	dir: *null | string
I wonder if we really need the `null` value. The working directory is always some path, and the default value of the current directory could be expressed as `"."`.

2020-09-30 13:42 UTC, mpvl commented on pkg/tool/exec/exec.cue
> +	dir: *null | string
I'm fine with using `null`, although using `"."` would simplify the code below.

2020-09-30 13:42 UTC, mpvl commented on pkg/tool/exec/exec.go
> +	if v := ctx.Obj.Lookup("dir"); v.Exists() {
Is this correct? This should also check if the value is null.

Would be good to test this in a `cmd/cue/cmd/testdata/*.txt` file.

2020-10-31 16:18 UTC, chai2010 commented on pkg/tool/exec/exec.go
> +	if v := ctx.Obj.Lookup("dir"); v.Exists() {
PTAL

2020-11-21 14:15 UTC, mpvl requested changes
Sorry for the delay. Took a bit closer look this time.

Almost done. No need for a test for `null` (see comments below).

2020-11-21 14:15 UTC, mpvl commented on pkg/tool/exec/exec.go
> +	if v := ctx.Obj.Lookup("dir"); v.Exists() {
The test doesn't check the `null` case. 

Actually, looking more closely at the surrounding code, this would suffice and be more in style:

```
cmd.Dir, _ = ctx.Obj.Lookup("dir").String()
```
this will ignore any error by just setting the empty directory. 

This relies on the template definition to be type checked against the input. So any other value would be ignored.

2020-11-21 14:15 UTC, mpvl commented on pkg/tool/exec/exec.cue
> +	dir: *null | string
An alternative here could simply be to use *"" as the default. For the stdout, for instance, `null` has some meaning over `""`. This is not the case here. I would remove `null` and either have no default or `*""` so that we later can use it to mean something else, if we ever need it.

2021-05-25 15:02 UTC, closed without merging