Proposed fix for embedded structs are not honoured
cuelang/cue pull request #568
Opened 2020-10-25 07:06 UTC by stromsvag

This is a proposed fix for #376 .

I added [a comment](https://github.com/cuelang/cue/issues/376#issuecomment-715940879) to #376 with some questions. Would be great if I could get some feedback on that as well as my proposed fix. My experience with cue is very limited.

2020-10-29 16:34 UTC, mpvl requested changes

2020-10-29 16:34 UTC, mpvl commented on encoding/gocode/gocodec/codec_test.go
> +		},
The purpose of this change is to let the CUE encoding mimic Go's encoding.

There should also be a test case where an embedded struct is assigned a name. For instance:
```
			type S struct {
					A string
					T `json:"t"`
				}
```
In that case, the type should not be embedded but named that way.

2020-10-29 16:34 UTC, mpvl commented on internal/core/convert/go.go
> +					obj.Decls = append(obj.Decls, sub)
I would expect you'ld either embed sub or add its arcs below, but not both. Adding the arcs is probably nicer.

2020-10-29 17:35 UTC, stromsvag commented on internal/core/convert/go.go
> +				sf := t.Field(i)
The only reason is that I found it a bit confusing to name it the same. I find `t` a great variable name for "type", but perhaps not the best for a struct field. Also, my IDE reported it as being shadowed. I am fine with reverting this change.

2020-10-29 17:47 UTC, stromsvag commented on internal/core/convert/go.go
> +					obj.Decls = append(obj.Decls, sub)
I currently have to do both in order to pass testing. I am still very new to this so I might have fundamentally misunderstood something.

2020-10-29 17:56 UTC, stromsvag commented on internal/core/convert/go.go
> +				if sf.Anonymous {
I don't think name will ever be empty. However, I could modify `getName` to return empty name if struct field is anonymous and not tagged. The condition could then be `if sf.Anonymous && name == ""`. That should fulfill the case you commented in tests.

2020-10-29 18:11 UTC, stromsvag commented on encoding/gocode/gocodec/codec_test.go
> +		},
I added a proposed solution for this. Let me know what you think.

2020-10-29 18:13 UTC, stromsvag commented on encoding/gocode/gocodec/codec_test.go
> +		{
Done :) I will start following this convention.

2020-10-31 06:47 UTC, stromsvag commented on internal/core/convert/go.go
> +					obj.Decls = append(obj.Decls, sub)
I took a stab at a change that I hope addresses your comment. See 326ff87.

2020-10-31 06:48 UTC, stromsvag commented on internal/core/convert/go.go
> +				if sf.Anonymous {
I decreased nesting by adding continue.

2020-11-18 12:11 UTC, mpvl reviewed
Moving it go Gerrit.

2020-11-18 12:20 UTC, closed without merging