Ensure we read from overlay when hitting readDir
cuelang/cue pull request #786
Opened 2021-02-21 03:02 UTC by tonyhb

`fileSystem.readDir` always reads from the actual filesystem, even if
there is an overaly directory present.  Read from the overlay directory
in these circumstances;  we shouldn't be hitting the disk.

Also, if the root path is "/" we can skip loading and return true.  This
allows fully in-memory packages as per
https://github.com/cuelang/cue/issues/607.

This helps with fix certain aspects in #607, but does not refactor `fileSystem`
to use any of the newer interfaces that we could.

2021-02-21 03:04 UTC, tonyhb commented
@googlebot I signed it!

2021-03-01 15:12 UTC, verdverm commented
How would this impact someone using Go created WASM from a NodeJS script, where the filesystem is available?

_I'm not super familiar, but this thought occurred to me_

2021-03-01 15:23 UTC, verdverm commented
https://github.com/cuelang/cue/tree/master/pkg/path

This may be the preferred way to handle GOOS specific differences

2021-03-01 16:49 UTC, verdverm commented
regarding WASM generally, my hunch is that it becomes a new JVM like platform with a LLVM flavor. That is to say that you get the intermediate assembly format that has a runtime for different platforms, and you get N language frontends that all compile to it. So I see it becoming more ubiquitous, not just for inside the browser. There are already projects pushing on this front, see https://github.com/wasmerio/wasmer

2021-03-01 18:55 UTC, tonyhb commented
Yep, I use these in my project (wasmtime, not wasmer - wasmer seems to be a UI over wasmtime) and these are _still_ isolated.  There is no spec for filesystems yet - there are still questions around interface types for integrating (eg. things better than pointers).

This is what I was mentioning in the third bullet point - you set up the VMs in `wasmtime` with any specific metering & usage you need.  Though filesystems aren't yet part of the wasm spec :)

2021-03-01 21:24 UTC, verdverm commented
We're still waiting for @mpvl and @myitcv to chime in. They are the core maintainers and have permissions on the repo. I just hangout a lot and contribute where / when I can. I'm not sure how they will feel about conditionals on GOOS, it seems like an anti-pattern to me personally. They also tend to prefer holistic solutions than piecemeal fixes for edge cases. This might be part of a larger WASM of FileSystem story. It would be worthwhile to open an broader discussion particulars and see where that takes us. There have been previous discussions around how to make Cue work well in the context of an API server that are probably related to this. Generally, it's better to start with an issue / discussion that ends up with a proposal and then work on code. Marcel and Paul come from the Go team, and so a lot of good philosophy and practices carry over with them. It may feel slow at times, but it results in much better designed and implemented software in the long term.

Separately, you can take a look at the contributing docs and get setup with Gerrit. Most development happens over there. This repo is more of a mirror than the source of truth. There are some sync services setup that I'm not familiar with (for a bit of context).

- https://github.com/cuelang/cue/blob/master/CONTRIBUTING.md
- https://github.com/cuelang/cue/blob/master/doc/contribute.md

2021-03-12 07:43 UTC, mpvl requested changes
Thanks for the changes.

This still needs a test to expose the problem.

2021-03-12 07:43 UTC, mpvl commented on cue/load/import.go
> +		if d[1] == "/" {
Will this also work for Windows volumes and other root indicators?

2021-03-12 07:43 UTC, mpvl commented on internal/internal.go
> +	if runtime.GOOS == "js" {
Why would "js" have to be special-cased here?

Is it because avoiding picking up the "pkg" directory?  This really should be disabled for all OSes, but probably only after a 3.0 release. Is there any reason why JS is special here? If so, please add a comment/ TODO.

2021-03-12 07:43 UTC, mpvl commented on cue/load/fs.go
> +	if fi := fs.getDir(path, false); fi != nil {
There is also a fs.getDir call below that is ostensibly there to achieve the same. So if the below code is buggy, it should be fixed there.

2021-03-12 13:02 UTC, myitcv commented
Sorry for the delay in getting around to this.

> Read from the overlay directory in these circumstances; we shouldn't be hitting the disk.

It's not clear to me that this is correct, and therefore I'm not clear that this change is solving the right problem. An overlay, in its current form, exists in order to _complement_ what is on disk, rather than wholesale replace its contents. 

```
-- blah.txt --
Hello
-- go.mod --
module blah.com

go 1.16

require cuelang.org/go v0.3.0-beta.6
-- main.go --
package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"

	"cuelang.org/go/cue"
	"cuelang.org/go/cue/load"
)

func main() {
	cwd, err := os.Getwd()
	if err != nil {
		log.Fatal(err)
	}
	abs := func(p string) string {
		return filepath.Join(cwd, p)
	}
	loadCfg := &load.Config{
		ModuleRoot: "/",
		Overlay: map[string]load.Source{
			abs("cue.mod/module.cue"): load.FromString(`module: "example.com"`),
			abs("x.cue"):              load.FromString("package x\nx: y"),
		},
	}
	bps := load.Instances([]string{"."}, loadCfg)
	is := cue.Build(bps)
	x, err := is[0].Lookup("x").Int64()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("x = %v\n", x)
}
-- y.cue --
package x

y: 5
```

In that respect it is a different beast to `io/fs.FS`. 

What I think you're looking for here is an `io/fs.FS`-based solution. That being the case, I suggest we open an issue discussing that. 

FWIW the [CUE playground](https://github.com/cue-sh/playground) (which is WASM-based) does not run into this because it [consumes its input over stdin](https://github.com/cue-sh/playground/blob/a768b6e5aed0a45438487493919a943af7fa57ad/impl.go#L54-L61).

2021-03-12 19:43 UTC, tonyhb commented on cue/load/fs.go
> +	if fi := fs.getDir(path, false); fi != nil {
This is one of the difficulties when lacking the `fs.DirEntry` interface.  We call ReadDir to iterate through, but this means we _must_ have a concrete directory to read from.  This breaks webassembly, as there is no underlying directory to read.  This is why we must special case unless we comform to `fs.DirEntry` and support only go > 1.16.

I do think that @myitcv was correct regarding this patch - it fixes this code such that we use overlays if possible - but the underlying root is the lack of  `io/fs` support.

To be honest, I'm fairly blocked on supporting cue with embedded packages without these fixes.  I really understand that we should strive towards an `io/fs` driver with interfaces - that's the correct solution here.

As you can probably tell, I'm not familiar with cue's internals enough to take this on - I could give it a shot, but there will be _lots_ of feedback.

2021-03-12 20:26 UTC, myitcv commented on cue/load/fs.go
> +	if fi := fs.getDir(path, false); fi != nil {
Then my suggestion is that we close this PR and move discussion to #607 or another issue if that one is not appropriate. In those issues, let's focus on specific use cases to help shape the solution.

2021-03-12 20:26 UTC, closed without merging

2021-03-12 20:26 UTC, myitcv commented
Closing per https://github.com/cuelang/cue/pull/786#discussion_r593429917

2021-03-13 02:13 UTC, tonyhb commented on cue/load/fs.go
> +	if fi := fs.getDir(path, false); fi != nil {
This PR aims to fix the bugs in #607 - we might want to start an entirely new discussion on the architecture of overlays, files, and cue loading using `io/fs` as the interface to account for windows, linux, and webassembly (virtual fs) usage.

2021-03-13 05:10 UTC, myitcv commented on cue/load/fs.go
> +	if fi := fs.getDir(path, false); fi != nil {
> This PR aims to fix the bugs in #607

Per my comments in https://github.com/cuelang/cue/pull/786#issuecomment-797476388, I'm not clear that the behaviour described in #607 is actually a bug (the issue itself is ostensibly a feature request). I'll comment on #607 to see if we can find a way forward.

2021-06-03 12:23 UTC, tonyhb commented
> Sorry for the delay in getting around to this.
> 
> > Read from the overlay directory in these circumstances; we shouldn't be hitting the disk.
> 
> It's not clear to me that this is correct, and therefore I'm not clear that this change is solving the right problem. An overlay, in its current form, exists in order to _complement_ what is on disk, rather than wholesale replace its contents.
> 
> ```
> -- blah.txt --
> Hello
> -- go.mod --
> module blah.com
> 
> go 1.16
> 
> require cuelang.org/go v0.3.0-beta.6
> -- main.go --
> package main
> 
> import (
> 	"fmt"
> 	"log"
> 	"os"
> 	"path/filepath"
> 
> 	"cuelang.org/go/cue"
> 	"cuelang.org/go/cue/load"
> )
> 
> func main() {
> 	cwd, err := os.Getwd()
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 	abs := func(p string) string {
> 		return filepath.Join(cwd, p)
> 	}
> 	loadCfg := &load.Config{
> 		ModuleRoot: "/",
> 		Overlay: map[string]load.Source{
> 			abs("cue.mod/module.cue"): load.FromString(`module: "example.com"`),
> 			abs("x.cue"):              load.FromString("package x\nx: y"),
> 		},
> 	}
> 	bps := load.Instances([]string{"."}, loadCfg)
> 	is := cue.Build(bps)
> 	x, err := is[0].Lookup("x").Int64()
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 	fmt.Printf("x = %v\n", x)
> }
> -- y.cue --
> package x
> 
> y: 5
> ```
> 
> In that respect it is a different beast to `io/fs.FS`.
> 
> What I think you're looking for here is an `io/fs.FS`-based solution. That being the case, I suggest we open an issue discussing that.
> 
> FWIW the [CUE playground](https://github.com/cue-sh/playground) (which is WASM-based) does not run into this because it [consumes its input over stdin](https://github.com/cue-sh/playground/blob/a768b6e5aed0a45438487493919a943af7fa57ad/impl.go#L54-L61).

Quickly wanted to reply to this and say that the playground does _not_ resolve this because it consumes from stdin - it resolves this because it has no `cue.mod` packages.  Any time you include a `cue.mod` package in wasm, `GenPath` fails.